DROP TABLE IF EXISTS Drinks CASCADE;
DROP TABLE IF EXISTS NonAlcoholicDrinks CASCADE;
DROP TABLE IF EXISTS AlcoholicDrinks CASCADE;

CREATE TABLE Drinks
(
    id integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--         constraint drinks_pkey
  --      primary key,
    name varchar(255) not null,
    purchasePrice float,
    volume float,
    quantity integer,
    drink_type varchar(10)
)
;


CREATE TABLE AlcoholicDrinks
(
    id integer
     --   constraint AlcoholicDrinks_pkey
            primary key
/*        constraint AlcoholicDrinks_Drinks_id_fk */
            references Drinks,
    type varchar(255) not null,
    abv integer not null
)
;


CREATE TABLE NonAlcoholicDrinks
(
    id integer
   --     constraint NonAlcoholicDrinks_pkey
            primary key
/*        constraint AlcoholicDrinks_Drinks_id_fk */
        references Drinks,
    type varchar(255) not null,
    composition text not null
)
;