DROP TABLE IF EXISTS Drinks CASCADE;
DROP TABLE IF EXISTS NonAlcoholicDrinks CASCADE;
DROP TABLE IF EXISTS AlcoholicDrinks CASCADE;
DROP TABLE IF EXISTS Orders CASCADE;
DROP TABLE IF EXISTS Ordersdetails CASCADE;

CREATE TABLE Drinks
(
    id integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--         constraint drinks_pkey
  --      primary key,
    name varchar(255) not null,
    purchasePrice float,
    volume float,
    quantity integer,
    drink_type varchar(10)
)
;


CREATE TABLE AlcoholicDrinks
(
    id integer
     --   constraint AlcoholicDrinks_pkey
            primary key
/*        constraint AlcoholicDrinks_Drinks_id_fk */
            references Drinks,
    type varchar(255) not null,
    abv float4 not null
)
;


CREATE TABLE NonAlcoholicDrinks
(
    id integer
   --     constraint NonAlcoholicDrinks_pkey
            primary key
/*        constraint AlcoholicDrinks_Drinks_id_fk */
        references Drinks,
    type varchar(255) not null,
    composition text not null
)
;

CREATE TABLE Orders
(
    id integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date,
    dayofweek smallint,
    time time,
    check_value float,
    shipping_info text
)
;


CREATE TABLE Ordersdetails
(
    id integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer,
    drink_id integer,
    drink_quantity smallint,
    drink_price float
)
;