DROP TABLE IF EXISTS Orders CASCADE;
DROP TABLE IF EXISTS Ordersdetails CASCADE;
CREATE TABLE Orders
(
    id integer
       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date,
    dayofweek smallint,
    time time,
    check_value float,
    shipping_info text
)
;

INSERT INTO Orders
(date, dayofweek, time, check_value, shipping_info)
VALUES
(current_date, extract(dow from now()), localtime, 324.56, 'some useful information');

CREATE TABLE Ordersdetails
(
    id integer
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer,
    drink_id integer,
    drink_quantity smallint
)
;

INSERT INTO Ordersdetails
(order_id, drink_id, drink_quantity)
VALUES
(1, 1, 21);
